#!/usr/bin/env bash
set -euo pipefail

ALERTMANAGER_URL=${ALERTMANAGER_URL:-http://localhost:9093}
SEVERITY=${1:-critical}
OWNER=${2:-ops}
RUNBOOK=${RUNBOOK_URL:-"docs/operations/monitoring-guide.md#alert-response"}

payload=$(cat <<JSON
[
  {
    "labels": {
      "alertname": "SmokeTestAlert",
      "severity": "$SEVERITY",
      "service": "smoke-test",
      "owner": "$OWNER",
      "escalation": "smoke"
    },
    "annotations": {
      "summary": "Alert delivery smoke test",
      "description": "Generated by scripts/monitoring/test-alert-delivery.sh",
      "runbook": "$RUNBOOK"
    },
    "generatorURL": "urn:smoketest"
  }
]
JSON
)

curl -fsS -X POST -H "Content-Type: application/json" -d "$payload" "$ALERTMANAGER_URL/api/v2/alerts"
echo "Smoke test alert sent to $ALERTMANAGER_URL"
